services:
  exemploprojeto:
    image: ${DOCKER_REGISTRY-}exemploprojeto
    build:
      context: ./ExemploProjeto
      dockerfile: ExemploProjeto/Dockerfile
    env_file:
      - Envs/.EnvExemplo
    ports:
      # Porta do container : Porta do host
      # se remover a porta ela vai ser randomica
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - mariadb

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.0
    container_name: redis-container
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]

  mariadb:
    image: mariadb:11.4.2
    container_name: mariadb-container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mysql_data:
  mariadb_data: